---
- name: Configure IOS OSPF
  hosts: rtr1,rtr3
  gather_facts: false
  connection: ansible.netcommon.network_cli

  tasks:
    - name: Apply OSPFv2 config
      cisco.ios.ios_config:
        lines: router-id {{ item.router_id }}
        parents: router ospf {{ item.process_id }}
      loop: "{{ ospfv2_config.processes }}"
